fid = {
    'Annie': 'an',
    'Beowulf': 'be',
    'Big Band': 'bb',
    'Cerebella': 'ce',
    'Double': 'do',
    'Eliza': 'el',
    'Filia': 'fi',
    'Fukua': 'fu',
    'Ms. Fortune': 'mf',
    'Painwheel': 'pw',
    'Parasoul': 'pa',
    'Peacock': 'pe',
    'Robo Fortune': 'rf',
    'Squigly': 'sq',
    'Umbrella': 'um',
    'Valentine': 'va'
}

### inject into website for easy vid check
# for (var card of cards) card.innerHTML = card.id;

vid = {
    # Annie
    'Ageless Wonder': 'aWond',
    'Fire Branded': 'heat',
    'Galactic Glamour': 'galaxy',
    'Heat Synced': 'hSync', # replaced with Fire Branded
    'Materia Girl': 'mGirl',
    'Model Leader': 'model',
    'Moonstruck': 'moon',
    'Ninja Star': 'ninja',
    'Solar Flair': 'solar',
    'Star Child': 'starC',
    'Star Shine': 'sShine',
    'Timeless Hero': 'hero',
    'Triple Threat': 'triple',
    # Beowulf
    'Beast King': 'bKing',
    'Cold Stones': 'cStones',
    'Dark Might': 'dMight',
    'Dragon Brawler': 'dBrawl',
    'Freedom Fighter': 'fFight',
    'Hype Man': 'hMan',
    'Number One': 'nOne',
    'Snake Bite': 'sBite',
    'Underdog': 'uDog',
    'Weekend Warrior': 'wWarr',
    'Wrestler X': 'wresX',
    'Wulfsbane': 'wBane',
    # Big Band
    'Bassline': 'bLine',
    'Beat Box': 'bBox',
    'Dream Band': 'dBand',
    'Epic Sax': 'eSax',
    'G.I. Jazz': 'gJazz',
    'Heavy Metal': 'hMetal',
    'Megasonic': 'mSonic',
    'Private Dick': 'pDick',
    'Resonant Evil': 'rEvil',
    'Robocopy': 'rCopy',
    'Treble Maker': 'tMake',
    'Vintage Virtuoso': 'vVirt',
    # Cerebella
    'Armed Forces': 'aForce',
    'Big Top': 'bTop',
    'Blitz__Glamour': 'bGlam',
    'Brain Freeze': 'bFreeze',
    'Criminal Mind': 'cMind',
    'Gray Matter': 'gMatt',
    'Harlequin': 'hQuin',
    'Headstrong': 'hStrong',
    'Heavy Handed': 'hHanded',
    'Star-Spangled': 'sSpang',
    'Toad Warrior': 'toad',
    'Understudy': 'uStudy',
    # Double
    'Creature of Habit': 'cHabit',
    'Doublicious': 'dLicious',
    'Evergreen Evil': 'eEvil',
    'Heart of Darkness': 'hDarkn',
    'Immoral Fiber': 'iFiber',
    'Jawbreaker': 'jBreaker',
    'Myst-Match': 'mMatch',
    'Nunsense': 'nSense',
    'Rainbow Blight': 'rBlight',
    'Sundae School': 'sSchool',
    'Temple Tyrant': 'tTyrant',
    'Xenomorph': 'xMorph',
    # Eliza
    'Bloodbath': 'bBath',
    'Bloody Valentine': 'bValen',
    'Decrypted': 'dCrypt',
    'Diva Intervention': 'dInterv',
    'In Denile': 'inDeni',
    'Inner Pieces': 'iPiece',
    'Lapis Luxury': 'lLux',
    'Mummy Dearest': 'mDear',
    'Red Velvet': 'rVelvet',
    'Revamped': 'sOut',
    'Scarlet Viper': 'sViper',
    'Tomb _ Gloom': 'gloom',
    # Filia
    'Bad Hair Day': 'bHDay',
    'Bad Ms Frosty': 'bMFrosty',
    'Class Cutter': 'cCutter',
    'Djinn Frizz': 'djFriz',
    'Dread Locks': 'dLocks',
    'Frayed Ends': 'fEnds',
    'Hair Apparent': 'hAppar',
    'Idol Threat': 'iThreat',
    'Parasite Weave': 'pWeave',
    'Rock Star': 'rStar',
    'Windswept': 'wSwept',
    # Fukua
    'Chameleon Twist': 'twist',
    'Dream_Demon': 'dDemon',
    'Feathered Edges': 'feath',
    'Infernal Twin': 'iTwin',
    'Night Terror': 'nTerr',
    'Phantom Threads': 'pThread',
    'Rain Shadow': 'rain',
    'Rough Copy': 'rCopy_',
    'Shadow Puppet': 'puppet',
    'Souls Sister': 'souls',
    'Splitting Image': 'sImage',
    'Vaporwave Vixen': 'vaporW',
    # Ms. Fortune
    'Claw _ Order': 'claw',
    'Feline Lucky': 'lucky',
    'Furry Fury': 'fFury',
    'Hack n_ Splash': 'splash',
    'Hellcat': 'hCat',
    'Just Kitten': 'jKit',
    'Meow _ Furever': 'meow',
    'Ms. Trial': 'mTrial',
    'Purrfect Dark': 'pDark',
    'Rogue Agent': 'rogue',
    'Time Thief': 'tThief',
    'Wind Stalker': 'wStalk',
    # Painwheel
    'Biting Cold': 'bCold',
    'Blood Drive': 'bDrive',
    'Buzzkill': 'bKill',
    'Firefly': 'fFly',
    'Fly Trap': 'fTrap',
    'Freaky Friday': 'fFriday',
    'Grim Fan': 'gFan',
    'Neuromancer': 'nMance',
    'Rage Appropriate': 'rAppr',
    'Raw Nerv': 'rNerv',
    'Rusty': 'rusty',
    'Twisted Mettle': 'tMett',
    # Parasoul
    'Heavy Reign': 'hReign',
    'High Ruler': 'hRuler',
    'Ivy League': 'iLeague',
    'No Egrets': 'nEgrets',
    'Primed': 'prime',
    'Princess Pride': 'pPride',
    'Regally Blonde': 'rBlonde',
    'Risky Ginger': 'rGing',
    'Shadow Ops': 'sOps',
    'Sheltered': 'shelt',
    'Star-Crossed': 'sCross',
    'Summer Salt': 'sSalt',
    # Peacock
    'Dream Catcher': 'dCatch',
    'Freeze Frame': 'fFrame',
    'Inkling': 'ink',
    'Mean One': 'mOne',
    'Pea Shooter': 'pShoot',
    'Prism Plumage': 'pPlum',
    'Rerun': 'rerun',
    'Sketchy': 'sketch',
    'That_s All Folks!': 'tAFolks',
    'Ultraviolent': 'uViolent',
    'Untouchable': 'uTouch',
    'Wildcard': 'wCard',
    # Robo-Fortune
    'Blue Bomber': 'bBomb',
    'Blue Screen': 'blueS',
    'Head Hunter': 'metro',
    'M-3OW': 'm3ow',
    'Nyanotech': 'nyan',
    'Overclocked': 'clock',
    'Persona Assistant': 'pAssist',
    'Prototype': 'pType',
    'Purrminator': 'purr',
    'Terror Byte': 'tByte',
    'Vector_Protector': 'vect',
    'X-Bot': 'xBot',
    # Squigly
    'Bio-Exorcist': 'bExor',
    'Dead Heat': 'dHeat',
    'Dead of Winter': 'dOWint',
    'Gang Green': 'gangG',
    'Love Crafted': 'loveCraft',
    'Nearly Departed': 'nDepart',
    'Necrobreaker': 'necroB',
    'Plot Twisted': 'pTwist',
    'Poltergust': 'polter',
    'Scared Stiff': 'sStiff',
    'Stage Fright': 'sFright',
    'Thrill Shrieker': 'shriek',
    # Umbrella
    'Candy_Crusher': 'candyCrusher',
    'Eager_Deceiver': 'eagerDeceiver',
    'Fresh_Heir': 'freshHeir',
    'Puddle_Pirate': 'puddlePirate',
    'Raining_Champ': 'reigningChamp',
    'Rose-Tinted': 'roseTinted',
    'Salty': 'salty',
    'Space_Case': 'spaceCase',
    'Tidal_Traveler': 'fullSail',
    'Wild_Child': 'wildChild',
    'Wunderkind': 'wunderKind',
    # Valentine
    'Assassin_s Greed': 'aGreed',
    'Graveyard Shift': 'gShift',
    'Icy Hot': 'iHot',
    'Kill Joy': 'kJoy',
    'Last Hope': 'lHope',
    'Oh Mai': 'oMai',
    'Petty in Pink': 'aGreed',
    'Pyro-Technique': 'pTech',
    'Scrub': 'scrub',
    'Silent Kill': 'sKill',
    'Surgeon General': 'sGeneral',
    'Tre_s Chic': 'tChic',
    'Wetwork': 'wWork'
}
