fID = {
    'Beowulf': 'be',
    'Big Band': 'bb',
    'Cerebella': 'ce',
    'Double': 'do',
    'Eliza': 'el',
    'Filia': 'fi',
    'Fukua': 'fu',
    'Ms. Fortune': 'mf',
    'Painwheel': 'pw',
    'Parasoul': 'pa',
    'Peacock': 'pe',
    'Robo-Fortune': 'rf',
    'Squigly': 'sq',
    'Valentine': 'va'
}

vID = {
    'Bassline': 'bLine',
    'Beat Box': 'bBox',
    'Epic Sax': 'eSax',
    'G.I. Jazz': 'gJazz',
    'Heavy Metal': 'hMetal',
    'Megasonic': 'mSonic',
    'Private Dick': 'pDick',
    'Resonant Evil': 'rEvil',
    'Robocopy': 'rCopy',

    'Cold Stones': 'cStones',
    'Dark Might': 'dMight',
    'Dragon Brawler': 'dBrawl',
    'Hype Man': 'hMan',
    'Number One': 'nOne',
    'Underdog': 'uDog',
    'Weekend Warrior': 'wWarr',
    'Wrestler X': 'wresX',
    'Wulfsbane': 'wBane',

    'Armed Forces': 'aForce',
    'Big Top': 'bTop',
    'Brain Freeze': 'bFreeze',
    'Gray Matter': 'gMatt',
    'Harlequin': 'hQuin',
    'Headstrong': 'hStrong',
    'Heavy Handed': 'hHanded',
    'Toad Warrior': 'toad',
    'Understudy': 'uStudy',

    'Doublicious': 'dLicious',
    'Immoral Fiber': 'iFiber',
    'Jawbreaker': 'jBreaker',
    'Myst-Match': 'fColor',
    'Nunsense': 'nSense',
    'Rainbow Blight': 'rBlight',
    'Sundae School': 'sSchool',
    'Temple Tyrant': 'tTyrant',
    'Xenomorph': 'xMorph',

    'Bloodbath': 'bBath',
    'Bloody Valentine': 'bValen',
    'Decrypted': 'dCrypt',
    'Diva Intervention': 'dInterv',
    'In Denile': 'inDeni',
    'Red Velvet': 'rVelvet',
    'Revamped': 'sOut',
    'Scarlet Viper': 'sViper',
    'Tomb _ Gloom': 'gloom',

    'Bad Hair Day': 'bHDay',
    'Bad Ms Frosty': 'bMFrosty',
    'Class Cutter': 'cCutter',
    'Dread Locks': 'dLocks',
    'Frayed Ends': 'fEnds',
    'Hair Apparent': 'hAppar',
    'Idol Threat': 'iThreat',
    'Parasite Weave': 'pWeave',
    'Windswept': 'wSwept',

    'Claw _ Order': 'claw',
    'Feline Lucky': 'lucky',
    'Furry Fury': 'fFury',
    'Hack n_ Splash': 'splash',
    'Hellcat': 'hCat',
    'Just Kitten': 'jKit',
    'Meow _ Furever': 'meow',
    'Ms. Trial': 'mTrial',
    'Purrfect Dark': 'pDark',

    'Heavy Reign': 'hReign',
    'Ivy League': 'iLeague',
    'No Egrets': 'nEgrets',
    'Primed': 'prime',
    'Princess Pride': 'pPride',
    'Regally Blonde': 'rBlonde',
    'Sheltered': 'shelt',
    'Star-Crossed': 'sCross',
    'Summer Salt': 'sSalt',

    'Freeze Frame': 'fFrame',
    'Inkling': 'ink',
    'Pea Shooter': 'pShoot',
    'Rerun': 'rerun',
    'Sketchy': 'sketch',
    'That_s All Folks!': 'tAFolks',
    'Ultraviolent': 'uViolent',
    'Untouchable': 'uTouch',
    'Wildcard': 'wCard',

    'Blood Drive': 'bDrive',
    'Buzzkill': 'bKill',
    'Firefly': 'fFly',
    'Fly Trap': 'fTrap',
    'Grim Fan': 'gFan',
    'Rage Appropriate': 'rAppr',
    'Raw Nerv': 'rNerv',
    'Rusty': 'rusty',
    'Twisted Mettle': 'tMett',

    'Bio-Exorcist': 'bExor',
    'Dead Heat': 'dHeat',
    'Dead of Winter': 'dOWint',
    'Love Crafted': 'lCrafted',
    'Nearly Departed': 'nDepart',
    'Necrobreaker': 'necroB',
    'Poltergust': 'polter',
    'Scared Stiff': 'sStiff',
    'Stage Fright': 'sFright',

    'Assassin_s Greed': 'aGreed',
    'Graveyard Shift': 'gShift',
    'Icy Hot': 'iHot',
    'Last Hope': 'lHope',
    'Oh Mai': 'oMai',
    'Petty in Pink': 'aGreed', # duplicate
    'Pyro-Technique': 'pTech',
    'Scrub': 'scrub',
    'Silent Kill': 'sKill',
    'Surgeon General': 'sGeneral'
}
