var spriteURLs = [
	"Beowulf_BB1_T1_GiganticArm.png",
	"Beowulf_BB2_T2_Airwulf.png",
	"Beowulf_BB3_T3_ThreeWulfMoonsault.png",
	"Beowulf_BB4_T1_GeatishTrepak.png",
	"Beowulf_BB5_T2_LupinePummel.png",
	"Beowulf_BB6_T3_Wulfamania.png",
	"Beowulf_ColdStones.png",
	"Beowulf_DarkMight.png",
	"Beowulf_DragonBrawler.png",
	"Beowulf_HypeMan.png",
	"Beowulf_NumberOne.png",
	"Beowulf_Portrait.png",
	"Beowulf_SM1_Outtake.png",
	"Beowulf_SM2_Burst.png",
	"Beowulf_SM3_Taunt.png",
	"Beowulf_SM4_WulfBlitzer.png",
	"Beowulf_SM5_WulfShoot.png",
	"Beowulf_SM6_GiganArmSweep.png",
	"Beowulf_SM8_HurtingHurdle.png",
	"Beowulf_SMX_HypeMode.png",
	"Beowulf_Underdog.png",
	"Beowulf_WeekendWarrior.png",
	"Beowulf_WrestlerX.png",
	"Beowulf_Wulfsbane.png",
	"BigBand_Bassline.png",
	"BigBand_BB1_T1_SuperSonicJazz.png",
	"BigBand_BB2_T3_StrikeUpTheBand.png",
	"BigBand_BB3_T2_TympaniDrive.png",
	"BigBand_BB4_T1_BeatExtend.png",
	"BigBand_BB5_T3_TubaTuba.png",
	"BigBand_BB6_T2_TakeTheATrain.png",
	"BigBand_Beatbox.png",
	"BigBand_EpicSax.png",
	"BigBand_GIJazz.png",
	"BigBand_HeavyMetal.png",
	"BigBand_Megasonic.png",
	"BigBand_Portrait.png",
	"BigBand_PrivateDick.png",
	"BigBand_ResonantEvil.png",
	"BigBand_Robocopy.png",
	"BigBand_SM1_BrassKnuckles.png",
	"BigBand_SM2_GiantStep.png",
	"BigBand_SM3_Taunt.png",
	"BigBand_SM4_Burst.png",
	"BigBand_SM5_CymbalSmash.png",
	"BigBand_SM6_TakeFive.png",
	"BigBand_SM7_SweetClarinet.png",
	"BigBand_SM8_NoiseCancel.png",
	"Cerebella_ArmedForces.png",
	"Cerebella_BB1_T2_DiamondsAreForever.png",
	"Cerebella_BB2_T1_DiamondDynamo.png",
	"Cerebella_BB3_T3_UltimateShowstopper.png",
	"Cerebella_BB4_T2_Excellebella.png",
	"Cerebella_BB5_T1_DiamondDrop.png",
	"Cerebella_BB6_T3_GrabBag.png",
	"Cerebella_BigTop.png",
	"Cerebella_BrainFreeze.png",
	"Cerebella_GrayMatter.png",
	"Cerebella_HairBrained.png",
	"Cerebella_Harlequin.png",
	"Cerebella_HeavyHanded.png",
	"Cerebella_Portrait.png",
	"Cerebella_SM1_Taunt.png",
	"Cerebella_SM2_ButtSlam.png",
	"Cerebella_SM3_Cerecopter.png",
	"Cerebella_SM4_LockNLoad.png",
	"Cerebella_SM5_PummelHorse.png",
	"Cerebella_SM6_BattleButt.png",
	"Cerebella_SM7_MerryGorilla.png",
	"Cerebella_SM8_Snapback.png",
	"Cerebella_SM9_Burst.png",
	"Cerebella_ToadWarrior.png",
	"Cerebella_Understudy.png",
	"Double_BB1_BeastOfGehenna.png",
	"Double_BB2_GunBlades.png",
	"Double_BB3_NightmareLegion.png",
	"Double_BB4_Bandwagon.png",
	"Double_BB5_CatelliteLives.png",
	"Double_BB6_MegalithArray.png",
	"Double_Doublicious.png",
	"Double_ImmoralFiber.png",
	"Double_Jawbreaker.png",
	"Double_MystMatch.png",
	"Double_Nunsense.png",
	"Double_Portrait.png",
	"Double_RainbowBlight.png",
	"Double_SM1_Outtake.png",
	"Double_SM2_Burst.png",
	"Double_SM3_Taunt.png",
	"Double_SM4_HornetBomber.png",
	"Double_SM5_LugerReplica.png",
	"Double_SM6_CiliaSlide.png",
	"Double_SM7_FleshStep.png",
	"Double_SM8_BogusBuzzard.png",
	"Double_SundaeSchool.png",
	"Double_TempleTyrant.png",
	"Double_Xenomorph.png",
	"Eliza_BB1_T1_SekhmetsBite.png",
	"Eliza_BB1_T1_SekhmetsFury.png",
	"Eliza_BB1_T1_SekhmetsTurn.png",
	"Eliza_BB1_T3_LadyOfSlaughter.png",
	"Eliza_BB2_T2_KhepriSun.png",
	"Eliza_BB3_T2_NekhbetBreaker.png",
	"Eliza_Bloodbath.png",
	"Eliza_BloodyValentine.png",
	"Eliza_Decrypted.png",
	"Eliza_DivaIntervention.png",
	"Eliza_InDenile.png",
	"Eliza_Portrait.png",
	"Eliza_RedVelvet.png",
	"Eliza_Revamped.png",
	"Eliza_ScarletViper.png",
	"Eliza_SM1_Taunt.png",
	"Eliza_SM2_Snapback.png",
	"Eliza_SM3_Burst.png",
	"Eliza_SM4_UpperKhat.png",
	"Eliza_SM5_OsirisSpiral.png",
	"Eliza_SM6_MiddleOfTheSphynx.png",
	"Eliza_SM7_ThroneOfIsis.png",
	"Eliza_SM8_WeightOfAnubis.png",
	"Eliza_SM9_DiveOfHorus.png",
	"Eliza_SM10_ChaosBanish.png",
	"Eliza_SMX_ElizaReturn.png",
	"Eliza_TombAndGloom.png",
	"Filia_BadHairDay.png",
	"Filia_BadMsFrosty.png",
	"Filia_BB1_T1_GregorSamson.png",
	"Filia_BB2_T2_Trichobezoar.png",
	"Filia_BB3_T3_FenrirDrive.png",
	"Filia_BB4_T2_WidowsPeak.png",
	"Filia_BB5_T1_DrillTempered.png",
	"Filia_BB6_T3_Blowout.png",
	"Filia_ClassCutter.png",
	"Filia_Dreadlocks.png",
	"Filia_FrayedEnds.png",
	"Filia_HairApparent.png",
	"Filia_IdolThreat.png",
	"Filia_ParasiteWeave.png",
	"Filia_Portrait.png",
	"Filia_SM1_FrenchTwist.png",
	"Filia_SM2_Hairball.png",
	"Filia_SM3_RingletSpike.png",
	"Filia_SM4_Burst.png",
	"Filia_SM5_Outtake.png",
	"Filia_SM6_Drillationship.png",
	"Filia_SM7_Taunt.png",
	"Filia_Windswept.png",
	"HeavyMetal.png",
	"MsFortune_BB1_HitPaws.png",
	"MsFortune_BB2_CatScratchFever.png",
	"MsFortune_BB3_OMNOMNOM.png",
	"MsFortune_BB4_FeralEdge.png",
	"MsFortune_BB5_FifthOfDismember.png",
	"MsFortune_BlackIce.png",
	"MsFortune_ClawAndOrder.png",
	"MsFortune_FelineLucky.png",
	"MsFortune_FurryFury.png",
	"MsFortune_Hellcat.png",
	"MsFortune_JustKitten.png",
	"MsFortune_MeowAndFurever.png",
	"MsFortune_MsTrial.png",
	"MsFortune_Portrait.png",
	"MsFortune_PurrfectDark.png",
	"MsFortune_SM1_Outtake.png",
	"MsFortune_SM2_Burst.png",
	"MsFortune_SM3_Taunt.png",
	"MsFortune_SM4_FiberUpper.png",
	"MsFortune_SM5_ElGato.png",
	"MsFortune_SM6_CatSlide.png",
	"MsFortune_SM7_CatScratch.png",
	"MsFortune_SMX_HeadGames_Bowl.png",
	"MsFortune_SMX_HeadGames_Headbutt.png",
	"MsFortune_SMX_HeadGames_Recall.png",
	"MsFortune_SMX_HeadGames_Sneeze.png",
	"MsFortune_SMX_HeadGames_Zoom.png",
	"MsFortune_SMX_HeadGames.png",
	"Painwheel_BB1_T1_DeathCrawl.png",
	"Painwheel_BB2_T2_BuerThresher.png",
	"Painwheel_BB3_T3_BuerOverdrive.png",
	"Painwheel_BB4_T1_HatredInstall.png",
	"Painwheel_BB5_T2_FractureReaper.png",
	"Painwheel_BloodDrive.png",
	"Painwheel_Buzzkill.png",
	"Painwheel_Firefly.png",
	"Painwheel_FlyTrap.png",
	"Painwheel_Portrait.png",
	"Painwheel_RageAppropriate.png",
	"Painwheel_RawNerv.png",
	"Painwheel_Rusty.png",
	"Painwheel_SkeletonDancer.png",
	"Painwheel_SM1_GaeBolgaStinger.png",
	"Painwheel_SM2_Snapdragon.png",
	"Painwheel_SM3_Taunt.png",
	"Painwheel_SM4_VioletGrudge.png",
	"Painwheel_SM5_CruelLily.png",
	"Painwheel_SM6_PinionDash.png",
	"Painwheel_SM7_Burst.png",
	"Painwheel_TwistedMettle.png",
	"Parasoul_BB1_T1_SilentScope.png",
	"Parasoul_BB2_T2_MotorBrigade.png",
	"Parasoul_BB3_T3_InfernoBrigade.png",
	"Parasoul_BB4_T1_Forbearance.png",
	"Parasoul_BB5_T2_NapalmShower.png",
	"Parasoul_HeavyReign.png",
	"Parasoul_IvyLeague.png",
	"Parasoul_NoEgrets.png",
	"Parasoul_Portrait.png",
	"Parasoul_Primed.png",
	"Parasoul_PrincessPride.png",
	"Parasoul_RegallyBlonde.png",
	"Parasoul_Sheltered.png",
	"Parasoul_SM1_Taunt.png",
	"Parasoul_SM2_Snapback.png",
	"Parasoul_SM3_Burst.png",
	"Parasoul_SM4_NapalmShot.png",
	"Parasoul_SM5_EgretCall.png",
	"Parasoul_SM6_EgretSacrifice.png",
	"Parasoul_SM7_EgretMoto.png",
	"Parasoul_SM8_NapalmToss.png",
	"Parasoul_SM9_NapalmTrigger.png",
	"Parasoul_StarCrossed.png",
	"Parasoul_SummerSalt.png",
	"Peacock_BB1_T2_LonesomeLenny.png",
	"Peacock_BB2_T3_Goodfellows.png",
	"Peacock_BB4_T2_Bandwagon.png",
	"Peacock_BB5_T1_ArgusAgony.png",
	"Peacock_BB6_T1_ImpendingDoom.png",
	"Peacock_BB7_T3_DeadlyAirport.png",
	"Peacock_FreezeFrame.png",
	"Peacock_Inkling.png",
	"Peacock_PeaShooter.png",
	"Peacock_Portrait.png",
	"Peacock_Rerun.png",
	"Peacock_Sketchy.png",
	"Peacock_SM1_Taunt.png",
	"Peacock_SM2_BANG.png",
	"Peacock_SM4_George_Walk.png",
	"Peacock_SM5_George_Boxcar.png",
	"Peacock_SM6_George_AirShow.png",
	"Peacock_SM8_Snapback.png",
	"Peacock_SM9_Burst.png",
	"Peacock_ThatsAllFolks.png",
	"Peacock_Ultraviolent.png",
	"Peacock_Untouchable.png",
	"Peacock_Wildcard.png",
	"RoboFortune_Portrait.png",
	"Squigly_BB1_DaisyPusher.png",
	"Squigly_BB2_BattleOpera.png",
	"Squigly_BB3_InfernoOfLeviathan.png",
	"Squigly_BB4_DragNDrop.png",
	"Squigly_BB5_RageOfTheDragon.png",
	"Squigly_BioExorcist.png",
	"Squigly_DeadHeat.png",
	"Squigly_DeadOfWinter.png",
	"Squigly_LoveCrafted.png",
	"Squigly_NearlyDeparted.png",
	"Squigly_Necrobreaker.png",
	"Squigly_Poltergust.png",
	"Squigly_Portrait.png",
	"Squigly_ScaredStiff.png",
	"Squigly_SM1_Outtake.png",
	"Squigly_SM2_Burst.png",
	"Squigly_SM3_Taunt.png",
	"Squigly_SM4_DragNBite.png",
	"Squigly_SM5_TheSilverChord.png",
	"Squigly_SM6_DraugenPunch.png",
	"Squigly_SM7_CenterStage.png",
	"Squigly_SM8_AshesToAshes.png",
	"Squigly_StageFright.png",
	"Squigly_WyrmsTail.png",
	"Valentine_BB1_T1_CheckmateIncision.png",
	"Valentine_BB2_T3_EKGFlatliner.png",
	"Valentine_BB3_T3_DeadOnArrival.png",
	"Valentine_BB4_T2_ForbiddenProcedure.png",
	"Valentine_BB5_T1_CountervenomAlpha.png",
	"Valentine_BB6_T1_CountervenomBeta.png",
	"Valentine_BB7_T1_CountervenomOmega.png",
	"Valentine_BB8_T2_Laryngectomy.png",
	"Valentine_GraveyardShift.png",
	"Valentine_IcyHot.png",
	"Valentine_LastHope.png",
	"Valentine_OhMai.png",
	"Valentine_PettyInPink.png",
	"Valentine_Portrait.png",
	"Valentine_PyroTechnique.png",
	"Valentine_Scrub.png",
	"Valentine_SergeonGeneral.png",
	"Valentine_SilentKill.png",
	"Valentine_SM1_Taunt.png",
	"Valentine_SM2_Snapback.png",
	"Valentine_SM3_Shuriken.png",
	"Valentine_SM4_Burst.png",
	"Valentine_SM5_VialHazardA.png",
	"Valentine_SM6_VialHazardB.png",
	"Valentine_SM7_VialHazardC.png",
	"Valentine_SM9_MortuaryDrop.png"
];

for (var spriteURL of spriteURLs) {
	var img = new Image();
	img.src = "Sprite/" + spriteURL;
	document.body.appendChild(img);
}

var style = document.getElementsByTagName("style")[0];
var r = document.getElementById("r");
var g = document.getElementById("g");
var b = document.getElementById("b");

function setBackground() {
	style.innerHTML = style.innerHTML.replace(
		/(background: #)([0-9a-fA-F]+)/g,
		"$1" + (r.checked ? "F" : "0") + (g.checked ? "F" : "0") + (b.checked ? "F" : "0")
	);
}

r.addEventListener("click", setBackground);
g.addEventListener("click", setBackground);
b.addEventListener("click", setBackground);

var a = document.getElementById("a");
var light = document.createElement("div");
var mouse = {};

function updateLight(e) {
	if (e.clientX && e.clientY) {
		mouse.x = e.clientX;
		mouse.y = e.clientY;
	}
	if (mouse.x && mouse.y) {
		light.style.left = window.scrollX + mouse.x + "px";
		light.style.top = window.scrollY + mouse.y + "px";
	}
}

function enableLight() {
	light.style.position = "absolute";
	light.style.width = "200vmax";
	light.style.height = "200vmax";
	light.style.transform = "translate(-50%, -50%)";
	light.style.background = "radial-gradient(#f00, #000 33%)";
	light.style.mixBlendMode = "overlay";
	light.style.pointerEvents = "none";
	window.addEventListener("mousemove", updateLight);
	window.addEventListener("scroll", updateLight);
	window.addEventListener("resize", updateLight);
	document.body.appendChild(light);
}

function disableLight() {
	window.removeEventListener("mousemove", updateLight);
	window.removeEventListener("scroll", updateLight);
	window.removeEventListener("resize", updateLight);
	light.remove();
}

function toggleLight() {
	if (a.checked) {
		enableLight();
	}
	else {
		disableLight();
	}
}

a.addEventListener("click", toggleLight);